### ISSUE TITLE
Client closes down immediately

### ISSUE THREAD

**Issue by uberhalit** [armata/blaze-server#5]
I got the master server up and running, gameserver connects and GameState is IN_GAME however when I try to start the client via _StartGame.bat the game pops up for a few seconds and closes down again. I tried multiple setups and configurations but could not get it working.

EDIT: nevermind, got it working. Turns out my firewall blocks some stuff even when ste to **allow**.
You need a clean BF3 1.6.0.0 install without any patched par- Core- or exe-files.

This is a really great repo her, thanks.

**Comment by armata** [comment]
Does the Blaze server show any signs of the client connecting? To be honest, this piece of software kinda reached EOL and it's not like it ever worked with 1+ players anyways.

A proper LAN patch could be made by patching the game/server not to use Blaze at all and adding a connect command that takes an IP/port as an argument. (in fact, this has already been done by NoFaTe but he most likely won't share it for obvious reasons) However, due to lack of time/motivation I haven't really ever looked into it.

**Comment by armata** [comment]
Ah, glad you got it working 👍

**Comment by uberhalit** [comment]
You mean it won't work for more than 1 player?

**Comment by armata** [comment]
As far as I recall, no, but you can go ahead and try.

**Comment by uberhalit** [comment]
Well I can at least connect 2 players, will test more later on.

![screenshotwin32-0001](https://user-images.githubusercontent.com/19159295/34455755-01162390-ed86-11e7-90a5-6594244c78ca.jpg)
